-- CREATE TABLE
CREATE TABLE USER (
    ID INT(3) AUTO_INCREMENT,
    APP_USER_ID INT(64),
    NICKNAME VARCHAR(20),
    ACCESS_TOKEN VARCHAR(100),
    REFRESH_TOKEN VARCHAR(100),
    CREATED_AT DATE,
    PRIMARY KEY(ID)
);

CREATE TABLE TRAFFIC(
    IDX INT(10) AUTO_INCREMENT,
    REQUEST TEXT,
    RESPONSE TEXT,
    OCCURED_TIME DATE,
    PRIMARY KEY(IDX)
);
