-- CREATE TABLE
CREATE TABLE USER (
    ID INT(3) AUTO_INCREMENT,
    APP_USER_ID INT(64),
    NICKNAME VARCHAR(20),
    ACCESS_TOKEN VARCHAR(100),
    REFRESH_TOKEN VARCHAR(100),
    CREATED_AT DATE,
    PRIMARY KEY(ID)
);

CREATE TABLE TRAFFIC(
    IDX INT(10) AUTO_INCREMENT,
    REQUEST TEXT,
    RESPONSE TEXT,
    OCCURED_TIME DATE,
    PRIMARY KEY(IDX)
);

-- INSERT MOCK-UP DATA
INSERT INTO USER (APP_USER_ID, NICKNAME, ACCESS_TOKEN, REFRESH_TOKEN, CREATED_AT) 
VALUES('1283423114', '김민구', 'GqVEf9QRVWgdZ1OfLnjIsE7sSF2aP5j5Tnijs3o9dZa2AAxsK3c5z2', 
'_KnLShs_gS6To7U4oEgR5Gxs41VjRqBWhCyr6o9dZ6AAAF06KNFzs', now());
